# Cloud Build設定ファイル
# エージェントDX（Resume Generator）のビルド・デプロイ

substitutions:
  _TAG: ${SHORT_SHA}

steps:
  # Step 1: Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'resume-generator'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app:${_TAG}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app:latest'
      - '.'

  # Step 2: イメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app'

  # Step 3: Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agent-dx'
      - '--image=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app:${_TAG}'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3003'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=agent-dx-database-url:latest'
      - '--set-secrets=GOOGLE_CLIENT_ID=agent-dx-google-client-id:latest'
      - '--set-secrets=GOOGLE_CLIENT_SECRET=agent-dx-google-client-secret:latest'
      - '--set-secrets=NEXTAUTH_SECRET=agent-dx-nextauth-secret:latest'
      - '--set-secrets=NEXTAUTH_URL=agent-dx-nextauth-url:latest'
      - '--set-secrets=GEMINI_API_KEY=agent-dx-gemini-api-key:latest'
      - '--set-secrets=HUBSPOT_ACCESS_TOKEN=agent-dx-hubspot-access-token:latest'
      - '--set-secrets=GMAIL_USER=agent-dx-gmail-user:latest'
      - '--set-secrets=GMAIL_APP_PASSWORD=agent-dx-gmail-app-password:latest'
      - '--add-cloudsql-instances=${PROJECT_ID}:asia-northeast1:schedule-sharing-db'

# イメージをArtifact Registryに保存
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app:${_TAG}'
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/agent-dx/app:latest'

# タイムアウト設定（20分）
timeout: '1200s'

# ビルドオプション
options:
  logging: CLOUD_LOGGING_ONLY
